#
# BackPacks 3.0.0
# By michael1011
#

# What kind of database should be used
#
# Available options: SQLite and MySQL
# MySQL requires additional configuration therefore a SQLite database which is simply
# a file in the data directory of BackPacks is used as default and fallback
database: "sqlite"

# Needed if a MySQL database should be used
mysql:
  host: "127.0.0.1"
  port: 3306
  database: "backpacks"
  username: "backpacks"
  password: "backpacks"

# This section is for configuring and creating new BackPacks
#
# Important:
#  - all materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#  - the slots of a backpack have to be divisible by 9
backpacks:
  littlebackpack:
    name: "&bLittle &3BackPack"

    description:
      - ""
      - "&fThis is a &blittle &3BackPack"
      - "&fRight click to open it"

    slots: 9

    material: "COMPASS"

  normalbackpack:
    name: "&eNormal &6BackPack"

    description:
      - ""
      - "&fThis is a &enormal &6BackPack"
      - "&fRight click to open it"

    slots: 27

    material: "FEATHER"
