name: BackPacks
author: michael1011
version: 3.0.0

main: at.michael1011.backpacks.Main

commands:
  bpgive:
    description: Give a player a backpack
    usage: /bpgive <backpack> [player]
    aliases: [bpg]

permissions:
  backpacks.*:
    description: all permissions of the plugin
    default: op
    children:
      backpacks.give: true

  backpacks.give:
    description: to use the command /bpgive
